// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0BAFk_6YD5NDxEE4bTLmdvnwzBVnbldE',
    appId: '1:728850357033:web:b9143ceee93e8a433d3538',
    messagingSenderId: '728850357033',
    projectId: 'fasum-app-51f31',
    authDomain: 'fasum-app-51f31.firebaseapp.com',
    storageBucket: 'fasum-app-51f31.firebasestorage.app',
    measurementId: 'G-NHJQ02W1WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrak4TWvPZbpzPgXDB7PpxB1Wq0BjrfsU',
    appId: '1:728850357033:android:367c53d4190254de3d3538',
    messagingSenderId: '728850357033',
    projectId: 'fasum-app-51f31',
    storageBucket: 'fasum-app-51f31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhE5Vr6TfV3ykgmC-5ppY20ys8FyHAUSk',
    appId: '1:728850357033:ios:c4c91cb93d59816a3d3538',
    messagingSenderId: '728850357033',
    projectId: 'fasum-app-51f31',
    storageBucket: 'fasum-app-51f31.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhE5Vr6TfV3ykgmC-5ppY20ys8FyHAUSk',
    appId: '1:728850357033:ios:c4c91cb93d59816a3d3538',
    messagingSenderId: '728850357033',
    projectId: 'fasum-app-51f31',
    storageBucket: 'fasum-app-51f31.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0BAFk_6YD5NDxEE4bTLmdvnwzBVnbldE',
    appId: '1:728850357033:web:7a344bade1ee1e023d3538',
    messagingSenderId: '728850357033',
    projectId: 'fasum-app-51f31',
    authDomain: 'fasum-app-51f31.firebaseapp.com',
    storageBucket: 'fasum-app-51f31.firebasestorage.app',
    measurementId: 'G-PS80JFDS6K',
  );
}
