// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBP2rDT3j2lYRf7JQg-5bUr0voAyOgeRQ',
    appId: '1:205587571774:web:71eedf765988dc811d5d6f',
    messagingSenderId: '205587571774',
    projectId: 'cio-app-df610',
    authDomain: 'cio-app-df610.firebaseapp.com',
    databaseURL: 'https://cio-app-df610-default-rtdb.firebaseio.com',
    storageBucket: 'cio-app-df610.firebasestorage.app',
    measurementId: 'G-DZLBMZ2KDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe_nLX6-CQ9IrIjdIJnQ9_K2FUA91Ncdg',
    appId: '1:205587571774:android:08159a7a6086328d1d5d6f',
    messagingSenderId: '205587571774',
    projectId: 'cio-app-df610',
    databaseURL: 'https://cio-app-df610-default-rtdb.firebaseio.com',
    storageBucket: 'cio-app-df610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWpJWSJuTPpMQSTWVOHypWoNGTzsRfNq8',
    appId: '1:205587571774:ios:d928ef1076c67e511d5d6f',
    messagingSenderId: '205587571774',
    projectId: 'cio-app-df610',
    databaseURL: 'https://cio-app-df610-default-rtdb.firebaseio.com',
    storageBucket: 'cio-app-df610.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWpJWSJuTPpMQSTWVOHypWoNGTzsRfNq8',
    appId: '1:205587571774:ios:d928ef1076c67e511d5d6f',
    messagingSenderId: '205587571774',
    projectId: 'cio-app-df610',
    databaseURL: 'https://cio-app-df610-default-rtdb.firebaseio.com',
    storageBucket: 'cio-app-df610.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBP2rDT3j2lYRf7JQg-5bUr0voAyOgeRQ',
    appId: '1:205587571774:web:2219a22755b8422c1d5d6f',
    messagingSenderId: '205587571774',
    projectId: 'cio-app-df610',
    authDomain: 'cio-app-df610.firebaseapp.com',
    databaseURL: 'https://cio-app-df610-default-rtdb.firebaseio.com',
    storageBucket: 'cio-app-df610.firebasestorage.app',
    measurementId: 'G-8N5Q8KQR23',
  );
}
