// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_options.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApTzBwaKQhl2IxcQKiXIabMRRqpSa-s3A',
    appId: '1:1033539643655:web:6aa700fae6f50755c6fda2',
    messagingSenderId: '1033539643655',
    projectId: 'p-pab-app',
    authDomain: 'p-pab-app.firebaseapp.com',
    databaseURL: 'https://p-pab-app-default-rtdb.firebaseio.com',
    storageBucket: 'p-pab-app.firebasestorage.app',
    measurementId: 'G-4LJKQ1MD2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdivKUang8nRfKPR0th2jsMWGOr02hs_c',
    appId: '1:1033539643655:android:96a2df3563511200c6fda2',
    messagingSenderId: '1033539643655',
    projectId: 'p-pab-app',
    databaseURL: 'https://p-pab-app-default-rtdb.firebaseio.com',
    storageBucket: 'p-pab-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLKhZ54-PH8tc2YZrg3gFXdnib0kNnDrw',
    appId: '1:1033539643655:ios:75eeed26b5d57b37c6fda2',
    messagingSenderId: '1033539643655',
    projectId: 'p-pab-app',
    databaseURL: 'https://p-pab-app-default-rtdb.firebaseio.com',
    storageBucket: 'p-pab-app.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLKhZ54-PH8tc2YZrg3gFXdnib0kNnDrw',
    appId: '1:1033539643655:ios:75eeed26b5d57b37c6fda2',
    messagingSenderId: '1033539643655',
    projectId: 'p-pab-app',
    databaseURL: 'https://p-pab-app-default-rtdb.firebaseio.com',
    storageBucket: 'p-pab-app.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApTzBwaKQhl2IxcQKiXIabMRRqpSa-s3A',
    appId: '1:1033539643655:web:869c9521e08fd0e7c6fda2',
    messagingSenderId: '1033539643655',
    projectId: 'p-pab-app',
    authDomain: 'p-pab-app.firebaseapp.com',
    databaseURL: 'https://p-pab-app-default-rtdb.firebaseio.com',
    storageBucket: 'p-pab-app.firebasestorage.app',
    measurementId: 'G-ED2XNDPZXX',
  );
}
